services:
  swiftatlas:
    container_name: swiftatlas-swiftatlas
    build:
      context: ./swiftatlas
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_started
    networks:
      - swiftatlas-network
    env_file:
      - ./swiftatlas/var.env
    command: uvicorn swiftatlas.main:app --host 0.0.0.0 --port 8080

  mongo:
    container_name: swiftatlas-mongo
    image: mongo:7.0
    volumes:
      - ./init-indexes.js:/docker-entrypoint-initdb.d/init-indexes.js:ro
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - swiftatlas-network

networks:
  swiftatlas-network:


volumes:
  mongodata:
    driver: local
